In [4]:
import pandas as pd
import numpy as np


In [5]:
data= pd.read_csv('data/diabetes_dataset00.csv')
data.head()

Target Genetic Markers Autoantibodies  \
0          Steroid-Induced Diabetes        Positive       Negative   
1  Neonatal Diabetes Mellitus (NDM)        Positive       Negative   
2                       Prediabetic        Positive       Positive   
3                   Type 1 Diabetes        Negative       Positive   
4                  Wolfram Syndrome        Negative       Negative   

  Family History Environmental Factors  Insulin Levels  Age  BMI  \
0             No               Present              40   44   38   
1             No               Present              13    1   17   
2            Yes               Present              27   36   24   
3             No               Present               8    7   16   
4            Yes               Present              17   10   17   

  Physical Activity Dietary Habits  ...  Pulmonary Function  \
0              High        Healthy  ...                  76   
1              High        Healthy  ...                  60   
2              High      Unhealthy  ...                  80   
3               Low      Unhealthy  ...                  89   
4              High        Healthy  ...                  41   

   Cystic Fibrosis Diagnosis  Steroid Use History  Genetic Testing  \
0                         No                   No         Positive   
1                        Yes                   No         Negative   
2                        Yes                   No         Negative   
3                        Yes                   No         Positive   
4                         No                   No         Positive   

  Neurological Assessments Liver Function Tests Digestive Enzyme Levels  \
0                        3               Normal                      56   
1                        1               Normal                      28   
2                        1             Abnormal                      55   
3                        2             Abnormal                      60   
4                        1               Normal                      24   

        Urine Test Birth Weight Early Onset Symptoms  
0  Ketones Present         2629                   No  
1  Glucose Present         1881                  Yes  
2  Ketones Present         3622                  Yes  
3  Ketones Present         3542                   No  
4  Protein Present         1770                   No  

[5 rows x 34 columns]

In [6]:
data.info()
  # check missing values


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   Target                         70000 non-null  object
 1   Genetic Markers                70000 non-null  object
 2   Autoantibodies                 70000 non-null  object
 3   Family History                 70000 non-null  object
 4   Environmental Factors          70000 non-null  object
 5   Insulin Levels                 70000 non-null  int64 
 6   Age                            70000 non-null  int64 
 7   BMI                            70000 non-null  int64 
 8   Physical Activity              70000 non-null  object
 9   Dietary Habits                 70000 non-null  object
 10  Blood Pressure                 70000 non-null  int64 
 11  Cholesterol Levels             70000 non-null  int64 
 12  Waist Circumference            70000 non-null  int64 
 13  B

In [7]:
data.describe()

Insulin Levels           Age           BMI  Blood Pressure  \
count    70000.000000  70000.000000  70000.000000    70000.000000   
mean        21.607443     32.020700     24.782943      111.339543   
std         10.785852     21.043173      6.014236       19.945000   
min          5.000000      0.000000     12.000000       60.000000   
25%         13.000000     14.000000     20.000000       99.000000   
50%         19.000000     31.000000     25.000000      113.000000   
75%         28.000000     49.000000     29.000000      125.000000   
max         49.000000     79.000000     39.000000      149.000000   

       Cholesterol Levels  Waist Circumference  Blood Glucose Levels  \
count        70000.000000         70000.000000          70000.000000   
mean           194.867200            35.051657            160.701657   
std             44.532466             6.803461             48.165547   
min            100.000000            20.000000             80.000000   
25%            163.000000            30.000000            121.000000   
50%            191.000000            34.000000            152.000000   
75%            225.000000            39.000000            194.000000   
max            299.000000            54.000000            299.000000   

       Weight Gain During Pregnancy  Pancreatic Health  Pulmonary Function  \
count                  70000.000000       70000.000000        70000.000000   
mean                      15.496414          47.564243           70.264671   
std                        9.633096          19.984683           11.965600   
min                        0.000000          10.000000           30.000000   
25%                        7.000000          32.000000           63.000000   
50%                       16.000000          46.000000           72.000000   
75%                       22.000000          64.000000           79.000000   
max                       39.000000          99.000000           89.000000   

       Neurological Assessments  Digestive Enzyme Levels  Birth Weight  
count              70000.000000             70000.000000  70000.000000  
mean                   1.804157                46.420529   3097.061071  
std                    0.680154                19.391089    713.837300  
min                    1.000000                10.000000   1500.000000  
25%                    1.000000                31.000000   2629.000000  
50%                    2.000000                48.000000   3103.000000  
75%                    2.000000                61.000000   3656.250000  
max                    3.000000                99.000000   4499.000000

In [8]:
 
data.isnull().sum()

Target                           0
Genetic Markers                  0
Autoantibodies                   0
Family History                   0
Environmental Factors            0
Insulin Levels                   0
Age                              0
BMI                              0
Physical Activity                0
Dietary Habits                   0
Blood Pressure                   0
Cholesterol Levels               0
Waist Circumference              0
Blood Glucose Levels             0
Ethnicity                        0
Socioeconomic Factors            0
Smoking Status                   0
Alcohol Consumption              0
Glucose Tolerance Test           0
History of PCOS                  0
Previous Gestational Diabetes    0
Pregnancy History                0
Weight Gain During Pregnancy     0
Pancreatic Health                0
Pulmonary Function               0
Cystic Fibrosis Diagnosis        0
Steroid Use History              0
Genetic Testing                  0
Neurological Assessm

In [9]:
print(data.columns.tolist())

['Target', 'Genetic Markers', 'Autoantibodies', 'Family History', 'Environmental Factors', 'Insulin Levels', 'Age', 'BMI', 'Physical Activity', 'Dietary Habits', 'Blood Pressure', 'Cholesterol Levels', 'Waist Circumference', 'Blood Glucose Levels', 'Ethnicity', 'Socioeconomic Factors', 'Smoking Status', 'Alcohol Consumption', 'Glucose Tolerance Test', 'History of PCOS', 'Previous Gestational Diabetes', 'Pregnancy History', 'Weight Gain During Pregnancy', 'Pancreatic Health', 'Pulmonary Function', 'Cystic Fibrosis Diagnosis', 'Steroid Use History', 'Genetic Testing', 'Neurological Assessments', 'Liver Function Tests', 'Digestive Enzyme Levels', 'Urine Test', 'Birth Weight', 'Early Onset Symptoms']


In [35]:
#this are the selected parametrs from the actual data which is named as data 
selected_features = data[[
    'Target',
    'Blood Glucose Levels',
    'Insulin Levels',
    'BMI',
    'Age',
    'Blood Pressure',
    'Cholesterol Levels',
    'Waist Circumference',
    'Family History',
    'Genetic Markers',
    'Physical Activity',
    'Dietary Habits',
    'Smoking Status',
    'Alcohol Consumption',
    'Glucose Tolerance Test',
    'Pancreatic Health',
    'Liver Function Tests',
    'Early Onset Symptoms'
]]
selected_features.head()

Target  Blood Glucose Levels  Insulin Levels  \
0          Steroid-Induced Diabetes                    88              35   
1  Neonatal Diabetes Mellitus (NDM)                    98               8   
2                       Prediabetic                    25              22   
3                   Type 1 Diabetes                    41               3   
4                  Wolfram Syndrome                   209              12   

   BMI  Age  Blood Pressure  Cholesterol Levels  Waist Circumference  \
0   26   44              64                 101                   30   
1    5    1              13                  21                    4   
2   12   36              61                  85                   16   
3    4    7              40                  51                    9   
4    5   10              43                  46                   13   

   Family History  Genetic Markers  Physical Activity  Dietary Habits  \
0               0                1                  0               0   
1               0                1                  0               0   
2               1                1                  0               1   
3               0                0                  1               1   
4               1                0                  0               0   

   Smoking Status  Alcohol Consumption  Glucose Tolerance Test  \
0               1                    0                       1   
1               0                    2                       1   
2               1                    0                       0   
3               1                    2                       0   
4               1                    2                       1   

   Pancreatic Health  Liver Function Tests  Early Onset Symptoms  
0                 26                     1                     0  
1                 16                     1                     1  
2                 46                     0                     1  
3                 39                     0                     0  
4                  0                     1                     0

In [36]:
from sklearn.preprocessing import LabelEncoder

col_encode=[
    'Blood Glucose Levels',
    'Insulin Levels',
    'BMI',
    'Age',
    'Blood Pressure',
    'Cholesterol Levels',
    'Waist Circumference',
    'Family History',
    'Genetic Markers',
    'Physical Activity',
    'Dietary Habits',
    'Smoking Status',
    'Alcohol Consumption',
    'Glucose Tolerance Test',
    'Pancreatic Health',
    'Liver Function Tests',
    'Early Onset Symptoms'
]

le=LabelEncoder()
for col in col_encode:
    selected_features[col]=le.fit_transform(selected_features[col])

selected_features.head(10)
    


/var/folders/w_/tlx3kfln2s9btjy8l26bm8dw0000gn/T/ipykernel_1033/727607569.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_features[col]=le.fit_transform(selected_features[col])
/var/folders/w_/tlx3kfln2s9btjy8l26bm8dw0000gn/T/ipykernel_1033/727607569.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_features[col]=le.fit_transform(selected_features[col])
/var/folders/w_/tlx3kfln2s9btjy8l26bm8dw0000gn/T/ipykernel_1033/727607569.py:25: SettingWithCopyWarning: 
A value is trying to be 

Target  Blood Glucose Levels  Insulin Levels  \
0          Steroid-Induced Diabetes                    88              35   
1  Neonatal Diabetes Mellitus (NDM)                    98               8   
2                       Prediabetic                    25              22   
3                   Type 1 Diabetes                    41               3   
4                  Wolfram Syndrome                   209              12   
5                              LADA                    62              12   
6                   Type 2 Diabetes                   106              24   
7         Wolcott-Rallison Syndrome                   126               5   
8                Secondary Diabetes                    80              42   
9                Secondary Diabetes                   112              16   

   BMI  Age  Blood Pressure  Cholesterol Levels  Waist Circumference  \
0   26   44              64                 101                   30   
1    5    1              13                  21                    4   
2   12   36              61                  85                   16   
3    4    7              40                  51                    9   
4    5   10              43                  46                   13   
5   14   41              67                 108                   12   
6   19   30              55                 137                   23   
7    6    3              20                  57                    9   
8   13   47              78                  85                   20   
9   12   72              76                 159                   16   

   Family History  Genetic Markers  Physical Activity  Dietary Habits  \
0               0                1                  0               0   
1               0                1                  0               0   
2               1                1                  0               1   
3               0                0                  1               1   
4               1                0                  0               0   
5               1                1                  2               0   
6               0                0                  2               0   
7               0                1                  1               1   
8               0                0                  0               0   
9               1                1                  1               1   

   Smoking Status  Alcohol Consumption  Glucose Tolerance Test  \
0               1                    0                       1   
1               0                    2                       1   
2               1                    0                       0   
3               1                    2                       0   
4               1                    2                       1   
5               0                    1                       0   
6               0                    1                       1   
7               1                    1                       1   
8               1                    1                       1   
9               0                    1                       0   

   Pancreatic Health  Liver Function Tests  Early Onset Symptoms  
0                 26                     1                     0  
1                 16                     1                     1  
2                 46                     0                     1  
3                 39                     0                     0  
4                  0                     1                     0  
5                 30                     1                     1  
6                 52                     0                     0  
7                  3                     1                     1  
8                 81                     1                     0  
9                 76                     0                     0

In [38]:
selected_features.head(50)

In [43]:
x=selected_features[['Blood Glucose Levels',
    'Insulin Levels',
    'BMI',
    'Age',
    'Blood Pressure',
    'Cholesterol Levels',
    'Waist Circumference',
    'Family History',
    'Genetic Markers',
    'Physical Activity',
    'Dietary Habits',
    'Smoking Status',
    'Alcohol Consumption',
    'Glucose Tolerance Test',
    'Pancreatic Health',
    'Liver Function Tests',
    'Early Onset Symptoms']]

y=selected_features['Target']  # This contains the actual diabetes type diagnosis

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [45]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [71]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=200,        # more trees for stability
    max_depth=15,            # limit tree depth
    min_samples_split=15,    # require more samples to split
    min_samples_leaf=5,      # require more samples at each leaf
    max_features='sqrt',     # random subset of features per split
    oob_score=True,          # enables internal validation
    random_state=42,
    n_jobs=-1           )   
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

print(y_pred)

['Secondary Diabetes' 'Type 2 Diabetes' 'Secondary Diabetes' ...
 'Wolfram Syndrome' 'Gestational Diabetes' 'Type 1 Diabetes']


In [72]:
from sklearn.metrics import accuracy_score , confusion_matrix, classification_report
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:',conf_matrix)  


Accuracy: 0.8523571428571428
Confusion Matrix: [[ 874  111   22   51    0    0    0    0   11    0    0    1    0]
 [   0  985    0   49    0   32    0    0    6    0    0    0    0]
 [  33  105  908    0    0   18    2    0    0    0    6    0    0]
 [   0    0    0  998    0    0    0    0  196    0    0    0    0]
 [   0    0    0    0 1018    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0 1089    0    0    0    0    0    0    0]
 [   0    0    5    0    0    0  676   11    0  128  233    0    0]
 [   0    0    6    0    0    0  156  523    0  229  134    0    0]
 [   0    0    0    0    0    0    0    0 1123    0    0    0    0]
 [   0    2   10    0    0    0  141   14    0  813  103    0    0]
 [   0    0    0    0    0    0    0    0    0    0 1064    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0  825  238]
 [   0    0    0    0    0    0    0    0    0    0    0   14 1037]]


In [74]:
# Save the trained model and scaler properly
import pickle

print("Saving model and scaler...")

# Save the RandomForest model
with open('randomforest.pkl', 'wb') as f:
    pickle.dump(rf_model, f)
print("✓ Model saved to randomforest.pkl")

# Save the scaler
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
print("✓ Scaler saved to scaler.pkl")

# Verify the saved files
print("\nVerifying saved files...")
model_test = pickle.load(open('randomforest.pkl', 'rb'))
scaler_test = pickle.load(open('scaler.pkl', 'rb'))
print(f"Model type: {type(model_test)}")
print(f"Scaler type: {type(scaler_test)}")
print(f"Model expects {model_test.n_features_in_} features")
print(f"Number of classes: {len(model_test.classes_)}")
print(f"Sample classes: {list(model_test.classes_[:5])}")


Saving model and scaler...
✓ Model saved to randomforest.pkl
✓ Scaler saved to scaler.pkl

Verifying saved files...
Model type: <class 'sklearn.ensemble._forest.RandomForestClassifier'>
Scaler type: <class 'sklearn.preprocessing._data.StandardScaler'>
Model expects 17 features
Number of classes: 13
Sample classes: ['Cystic Fibrosis-Related Diabetes (CFRD)', 'Gestational Diabetes', 'LADA', 'MODY', 'Neonatal Diabetes Mellitus (NDM)']


In [73]:
# ================================
# OVERFITTING CHECK
# ================================

print("="*70)
print("🔍 CHECKING FOR OVERFITTING")
print("="*70)

# 1. Calculate training accuracy
y_train_pred = rf_model.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred)

# 2. Compare with test accuracy
test_accuracy = accuracy_score(y_test, y_pred)

print(f"\n📊 ACCURACY COMPARISON:")
print(f"   Training Accuracy: {train_accuracy:.4f} ({train_accuracy*100:.2f}%)")
print(f"   Test Accuracy:     {test_accuracy:.4f} ({test_accuracy*100:.2f}%)")
print(f"   Difference:        {abs(train_accuracy - test_accuracy):.4f} ({abs(train_accuracy - test_accuracy)*100:.2f}%)")

# 3. Interpret results
print(f"\n🎯 OVERFITTING ASSESSMENT:")
accuracy_gap = train_accuracy - test_accuracy

if accuracy_gap < 0.05:
    print("   ✅ NO OVERFITTING - Model generalizes well!")
    print("   The model performs similarly on both training and test data.")
elif accuracy_gap < 0.10:
    print("   ⚠️ SLIGHT OVERFITTING - Acceptable for most cases")
    print("   Small gap between training and test accuracy.")
elif accuracy_gap < 0.15:
    print("   ⚠️ MODERATE OVERFITTING - Consider regularization")
    print("   Noticeable gap between training and test accuracy.")
else:
    print("   ❌ SEVERE OVERFITTING - Model memorizing training data!")
    print("   Large gap indicates poor generalization.")

 

🔍 CHECKING FOR OVERFITTING

📊 ACCURACY COMPARISON:
   Training Accuracy: 0.8878 (88.78%)
   Test Accuracy:     0.8524 (85.24%)
   Difference:        0.0354 (3.54%)

🎯 OVERFITTING ASSESSMENT:
   ✅ NO OVERFITTING - Model generalizes well!
   The model performs similarly on both training and test data.

📊 ACCURACY COMPARISON:
   Training Accuracy: 0.8878 (88.78%)
   Test Accuracy:     0.8524 (85.24%)
   Difference:        0.0354 (3.54%)

🎯 OVERFITTING ASSESSMENT:
   ✅ NO OVERFITTING - Model generalizes well!
   The model performs similarly on both training and test data.
